Support doorbell motion zone (de)activation
tchellomello/python-ring-doorbell pull request #110
Opened 2019-01-07 03:26 UTC by arkpog

Add method for activating/deactivating/deleting doorbell motion zones.

2019-02-11 02:19 UTC, tchellomello commented on ring_doorbell/doorbot.py
> +        if not zone_id in DOORBELL_MOTION_ZONES:
@arkpog  could you please re-write this conditional statement?

2019-02-11 02:20 UTC, tchellomello commented on ring_doorbell/doorbot.py
> +            'doorbot[settings][motion_zones][{0}][state]'.format(zone_id): value
@arkpog please keep it within 79 chars

2019-02-13 02:41 UTC, arkpog commented on ring_doorbell/doorbot.py
> +            'doorbot[settings][motion_zones][{0}][state]'.format(zone_id): value
```suggestion
            'doorbot[settings][motion_zones][{0}][state]'.format(zone_id):\
                value
```

2019-02-13 02:43 UTC, arkpog commented on ring_doorbell/doorbot.py
> +        if not zone_id in DOORBELL_MOTION_ZONES:
```suggestion
        if zone_id not in DOORBELL_MOTION_ZONES:
```

2019-10-06 15:36 UTC, FearNaBoinne commented
What's the state of this request? It looks like it was abandoned Feb this year, but it would be great to be able to control the zones, so I can link them to my Domoticz system and enable/disable zones together with the rest of the alarm system...

2019-10-06 15:37 UTC, FearNaBoinne commented
Also, is there something I can do to help move this forward?

2021-01-18 05:09 UTC, tchellomello requested changes
@arkpog sorry for the long delay in reviewing this. I'm back on looking at this project more closely.
Could you re-work your PR so we can get this merged? Basically lint issues and re-testing it against the latest master branch so we can validate the change? Thanks

2021-07-14 15:17 UTC, jfmennedy commented
Tried this but getting back:
`requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.ring.com/clients_api/doorbots/5xxx9xxx?api_version=9&doorbot%5Bdescription%5D=Haustuer&doorbot%5Bsettings%5D%5Bmotion_zones%5D%5Bzone2%5D%5Bstate%5D=0
`
Is there a chance to get this to work? Or even to pause motiondetection for a given period (30min,1h,2h,3h,4h) as in the app?

Thx Jan

2021-07-14 15:56 UTC, jfmennedy commented on ring_doorbell/doorbot.py
>          url = API_URI + DOORBELLS_ENDPOINT.format(self.account_id)
url = DOORBELLS_ENDPOINT.format(self.account_id)

2021-07-14 15:58 UTC, jfmennedy commented on ring_doorbell/doorbot.py
>          url = API_URI + DOORBELLS_ENDPOINT.format(self.account_id)
url = DOORBELLS_ENDPOINT.format(self.account_id)

2023-11-27 10:29 UTC, closed without merging